import Database from 'better-sqlite3';
import { dirname } from 'path';
import { config, ensureDirExists } from './config';
import { runMigrations } from './migrations';
import { eventBus } from './event-bus';
import { hashPassword } from './password';
import { logger } from './logger';
import { parseMentions as parseMentionTokens } from './mentions';
import { ensureAutoGeneratedCredentials } from './auto-credentials';
import { getPrismaClient } from './prisma';

let sqliteBootstrapCompleted = false;
let runtimeListenersInitialized = false;
const isBuildPhase = process.env.NEXT_PHASE === 'phase-production-build'
const isTestMode = process.env.MISSION_CONTROL_TEST_MODE === '1'

/**
 * Legacy SQLite bootstrap:
 * keep the existing better-sqlite3 migration chain so existing installs
 * continue to work, while shifting all runtime reads/writes to Prisma.
 */
function bootstrapSqliteSchemaIfNeeded() {
  if (sqliteBootstrapCompleted) return;
  sqliteBootstrapCompleted = true;

  ensureAutoGeneratedCredentials();
  ensureDirExists(dirname(config.dbPath));
  const sqlite = new Database(config.dbPath);

  // Enable WAL mode for better concurrent access.
  sqlite.pragma('journal_mode = WAL');
  sqlite.pragma('synchronous = NORMAL');
  sqlite.pragma('cache_size = 1000');
  sqlite.pragma('foreign_keys = ON');
  // Retry for up to 5 s before throwing SQLITE_BUSY; prevents contention errors.
  sqlite.pragma('busy_timeout = 5000');

  runMigrations(sqlite);

  // Backfill post-baseline columns that used to be created ad hoc in route handlers.
  try {
    const columns = sqlite.prepare('PRAGMA table_info(agents)').all() as Array<{ name: string }>;
    const hasWorkingMemory = columns.some((col) => col.name === 'working_memory');
    if (!hasWorkingMemory) {
      sqlite.exec(`ALTER TABLE agents ADD COLUMN working_memory TEXT NOT NULL DEFAULT ''`);
    }
  } catch {
    // ignore
  }

  sqlite.close();
}

function ensureRuntimeListenersInitialized() {
  if (runtimeListenersInitialized) return;
  runtimeListenersInitialized = true;

  import('./webhooks').then(({ initWebhookListener }) => {
    initWebhookListener();
  }).catch(() => {
    // Silent - webhooks are optional
  });

  // Start built-in scheduler for runtime installs only.
  // Skip during `next build` and E2E/test mode to keep startup deterministic.
  if (!isBuildPhase && !isTestMode) {
    import('./scheduler').then(({ initScheduler }) => {
      initScheduler();
    }).catch(() => {
      // Silent - scheduler is optional
    });
  }
}

// Known-insecure passwords that should never be used in production.
// Includes the .env.example default and common placeholder values.
const INSECURE_PASSWORDS = new Set([
  'admin',
  'password',
  'change-me-on-first-login',
  'changeme',
  'testpass123',
])

export function resolveSeedAuthPassword(env: NodeJS.ProcessEnv = process.env): string | null {
  const b64 = env.AUTH_PASS_B64
  if (b64 && b64.trim().length > 0) {
    const normalized = b64.trim()
    const base64Pattern = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/
    if (!base64Pattern.test(normalized)) {
      logger.warn('AUTH_PASS_B64 is not valid base64; falling back to AUTH_PASS')
      return env.AUTH_PASS || null
    }

    try {
      const decoded = Buffer.from(normalized, 'base64').toString('utf8')
      const canonical = Buffer.from(decoded, 'utf8').toString('base64')
      if (canonical !== normalized) {
        logger.warn('AUTH_PASS_B64 failed base64 verification; falling back to AUTH_PASS')
        return env.AUTH_PASS || null
      }
      if (decoded.length > 0) return decoded
      logger.warn('AUTH_PASS_B64 is set but decoded to an empty value; falling back to AUTH_PASS')
    } catch {
      logger.warn('AUTH_PASS_B64 is not valid base64; falling back to AUTH_PASS')
    }
  }

  return env.AUTH_PASS || null
}

async function seedAdminUserFromEnvPrisma(): Promise<void> {
  // Skip seeding during `next build` — env vars may not be available yet
  if (process.env.NEXT_PHASE === 'phase-production-build') return
  const prisma = getPrismaClient()
  const count = await prisma.users.count().catch(() => 0)
  if (count > 0) return

  const username = process.env.AUTH_USER || 'admin'
  const password = resolveSeedAuthPassword()

  if (!password) {
    // No AUTH_PASS set — admin will be created via /setup web wizard instead
    logger.info(
      'AUTH_PASS is not set — admin account will be created via /setup. ' +
      'Set AUTH_PASS or AUTH_PASS_B64 to seed an admin from env (useful for CI/automation).'
    )
    return
  }

  if (INSECURE_PASSWORDS.has(password)) {
    logger.warn(
      `AUTH_PASS matches a known insecure default ("${password}"). ` +
      'Please set a strong, unique password in your .env file. ' +
      'Skipping admin user seeding until credentials are changed.'
    )
    return
  }

  const displayName = username.charAt(0).toUpperCase() + username.slice(1)
  const now = Math.floor(Date.now() / 1000)

  try {
    await prisma.users.create({
      data: {
        username,
        display_name: displayName,
        password_hash: hashPassword(password),
        role: 'admin',
        created_at: now,
        updated_at: now,
      },
      select: { id: true },
    })
  } catch (err: any) {
    // Unique constraint (already seeded).
    if (err?.code !== 'P2002') throw err
  }

  logger.info(`Seeded admin user: ${username}`)
}

// Type definitions for database entities
export interface Task {
  id: number;
  title: string;
  description?: string;
  status: 'inbox' | 'assigned' | 'in_progress' | 'review' | 'quality_review' | 'done';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  project_id?: number;
  project_ticket_no?: number;
  project_name?: string;
  project_prefix?: string;
  ticket_ref?: string;
  assigned_to?: string;
  created_by: string;
  created_at: number;
  updated_at: number;
  due_date?: number;
  estimated_hours?: number;
  actual_hours?: number;
  outcome?: 'success' | 'failed' | 'partial' | 'abandoned';
  error_message?: string;
  resolution?: string;
  feedback_rating?: number;
  feedback_notes?: string;
  retry_count?: number;
  completed_at?: number;
  tags?: string; // JSON string
  metadata?: string; // JSON string
}

export interface Agent {
  id: number;
  name: string;
  role: string;
  session_key?: string;
  soul_content?: string;
  status: 'offline' | 'idle' | 'busy' | 'error';
  last_seen?: number;
  last_activity?: string;
  created_at: number;
  updated_at: number;
  config?: string; // JSON string
}

export interface Comment {
  id: number;
  task_id: number;
  author: string;
  content: string;
  created_at: number;
  parent_id?: number;
  mentions?: string; // JSON string
}

export interface Activity {
  id: number;
  type: string;
  entity_type: string;
  entity_id: number;
  actor: string;
  description: string;
  data?: string; // JSON string
  created_at: number;
}

export interface Message {
  id: number;
  conversation_id: string;
  from_agent: string;
  to_agent?: string;
  content: string;
  message_type: string;
  metadata?: string; // JSON string
  read_at?: number;
  created_at: number;
}

export interface Notification {
  id: number;
  recipient: string;
  type: string;
  title: string;
  message: string;
  source_type?: string;
  source_id?: number;
  read_at?: number;
  delivered_at?: number;
  created_at: number;
}

export interface Tenant {
  id: number
  slug: string
  display_name: string
  linux_user: string
  plan_tier: string
  status: 'pending' | 'provisioning' | 'active' | 'suspended' | 'error'
  openclaw_home: string
  workspace_root: string
  gateway_port?: number
  dashboard_port?: number
  config?: string
  created_by: string
  owner_gateway?: string
  created_at: number
  updated_at: number
}

export interface Workspace {
  id: number
  slug: string
  name: string
  tenant_id: number
  created_at: number
  updated_at: number
}

export interface ProvisionJob {
  id: number
  tenant_id: number
  job_type: 'bootstrap' | 'update' | 'decommission'
  status: 'queued' | 'approved' | 'running' | 'completed' | 'failed' | 'rejected' | 'cancelled'
  dry_run: 0 | 1
  requested_by: string
  approved_by?: string
  runner_host?: string
  idempotency_key?: string
  request_json?: string
  plan_json?: string
  result_json?: string
  error_text?: string
  started_at?: number
  completed_at?: number
  created_at: number
  updated_at: number
}

export interface ProvisionEvent {
  id: number
  job_id: number
  level: 'info' | 'warn' | 'error'
  step_key?: string
  message: string
  data?: string
  created_at: number
}

/**
 * Returns true when the database has zero users — i.e. first-time setup is needed.
 * Safe to call during normal operation (fast single-row query).
 */
export async function needsFirstTimeSetup(): Promise<boolean> {
  try {
    const prisma = getPrismaClient()
    const count = await prisma.users.count()
    return count === 0
  } catch {
    return false
  }
}

// Database helper functions
export const db_helpers = {
  /**
   * Log an activity to the activity stream
   */
  logActivity: (
    type: string,
    entity_type: string,
    entity_id: number,
    actor: string,
    description: string,
    data?: any,
    workspaceId: number = 1
  ) => {
    const prisma = getPrismaClient()
    const now = Math.floor(Date.now() / 1000)
    void (async () => {
      const created = await prisma.activities.create({
        data: {
          type,
          entity_type,
          entity_id,
          actor,
          description,
          data: data ? JSON.stringify(data) : null,
          created_at: now,
          workspace_id: workspaceId,
        },
        select: { id: true },
      })

      eventBus.broadcast('activity.created', {
        id: created.id,
        type,
        entity_type,
        entity_id,
        actor,
        description,
        data: data || null,
        created_at: now,
        workspace_id: workspaceId,
      })
    })().catch(() => {
      // Best-effort; activity logging should not break request flows.
    })
  },

  /**
   * Create notification for @mentions
   */
  createNotification: (
    recipient: string,
    type: string,
    title: string,
    message: string,
    source_type?: string,
    source_id?: number,
    workspaceId: number = 1
  ) => {
    const prisma = getPrismaClient()
    const now = Math.floor(Date.now() / 1000)
    void (async () => {
      const created = await prisma.notifications.create({
        data: {
          recipient,
          type,
          title,
          message,
          source_type: source_type ?? null,
          source_id: source_id ?? null,
          created_at: now,
          workspace_id: workspaceId,
        },
        select: { id: true },
      })

      eventBus.broadcast('notification.created', {
        id: created.id,
        recipient,
        type,
        title,
        message,
        source_type: source_type || null,
        source_id: source_id || null,
        created_at: now,
        workspace_id: workspaceId,
      })
    })().catch(() => {
      // Best-effort; notifications should not break request flows.
    })

    return null as any
  },

  /**
   * Parse @mentions from text
   */
  parseMentions: (text: string): string[] => {
    return parseMentionTokens(text);
  },

  /**
   * Update agent status and last seen
   */
  updateAgentStatus: (agentName: string, status: Agent['status'], activity?: string, workspaceId: number = 1) => {
    const prisma = getPrismaClient()
    const now = Math.floor(Date.now() / 1000)
    void (async () => {
      const agent = await prisma.agents.findFirst({
        where: { name: agentName, workspace_id: workspaceId },
        select: { id: true },
      })

      await prisma.agents.updateMany({
        where: { name: agentName, workspace_id: workspaceId },
        data: { status, last_seen: now, last_activity: activity || null, updated_at: now },
      })

      if (agent) {
        eventBus.broadcast('agent.status_changed', {
          id: agent.id,
          name: agentName,
          status,
          last_seen: now,
          last_activity: activity || null,
        })
      }

      await prisma.activities.create({
        data: {
          type: 'agent_status_change',
          entity_type: 'agent',
          entity_id: agent?.id || 0,
          actor: agentName,
          description: `Agent status changed to ${status}`,
          data: JSON.stringify({ status, activity }),
          created_at: now,
          workspace_id: workspaceId,
        },
        select: { id: true },
      })
    })().catch(() => {
      // Best-effort status updates.
    })
  },

  /**
   * Get recent activities for feed
   */
  getRecentActivities: async (limit: number = 50): Promise<Activity[]> => {
    const prisma = getPrismaClient()
    return prisma.activities.findMany({
      orderBy: { created_at: 'desc' },
      take: limit,
    }) as any
  },

  /**
   * Get unread notifications for recipient
   */
  getUnreadNotifications: async (recipient: string, workspaceId: number = 1): Promise<Notification[]> => {
    const prisma = getPrismaClient()
    return prisma.notifications.findMany({
      where: { recipient, read_at: null, workspace_id: workspaceId },
      orderBy: { created_at: 'desc' },
    }) as any
  },

  /**
   * Mark notification as read
   */
  markNotificationRead: (notificationId: number, workspaceId: number = 1) => {
    const now = Math.floor(Date.now() / 1000)
    const prisma = getPrismaClient()
    void prisma.notifications.updateMany({
      where: { id: notificationId, workspace_id: workspaceId },
      data: { read_at: now },
    }).catch(() => {
      // ignore
    })
  },

  /**
   * Ensure an agent is subscribed to a task
   */
  ensureTaskSubscription: (taskId: number, agentName: string, workspaceId: number = 1) => {
    if (!agentName) return;
    const prisma = getPrismaClient()
    const now = Math.floor(Date.now() / 1000)
    void (async () => {
      const task = await prisma.tasks.findFirst({
        where: { id: taskId, workspace_id: workspaceId },
        select: { id: true },
      })
      if (!task) return

      try {
        await prisma.task_subscriptions.create({
          data: { task_id: taskId, agent_name: agentName, created_at: now },
          select: { id: true },
        })
      } catch (err: any) {
        // Unique constraint violation (already subscribed)
        if (err?.code !== 'P2002') throw err
      }
    })().catch(() => {
      // ignore
    })
  },

  /**
   * Get subscribers for a task
   */
  getTaskSubscribers: async (taskId: number, workspaceId: number = 1): Promise<string[]> => {
    const prisma = getPrismaClient()
    const rows = await prisma.task_subscriptions.findMany({
      where: { task_id: taskId, tasks: { workspace_id: workspaceId } },
      select: { agent_name: true },
    })
    return rows.map((row) => row.agent_name)
  },
};

/**
 * Log a security/admin audit event
 */
export function logAuditEvent(event: {
  action: string
  actor: string
  actor_id?: number
  target_type?: string
  target_id?: number
  detail?: any
  ip_address?: string
  user_agent?: string
}) {
  const prisma = getPrismaClient()
  const now = Math.floor(Date.now() / 1000)
  void prisma.audit_log.create({
    data: {
      action: event.action,
      actor: event.actor,
      actor_id: event.actor_id ?? null,
      target_type: event.target_type ?? null,
      target_id: event.target_id ?? null,
      detail: event.detail ? JSON.stringify(event.detail) : null,
      ip_address: event.ip_address ?? null,
      user_agent: event.user_agent ?? null,
      created_at: now,
    },
    select: { id: true },
  }).catch(() => {
    // Best-effort: audit logs should not take down the request path.
  })

  // Broadcast audit events (webhooks listen here too)
  const securityEvents = ['login_failed', 'user_created', 'user_deleted', 'password_change']
  if (securityEvents.includes(event.action)) {
    eventBus.broadcast('audit.security', {
      action: event.action,
      actor: event.actor,
      target_type: event.target_type ?? null,
      target_id: event.target_id ?? null,
      timestamp: Math.floor(Date.now() / 1000),
    })
  }
}

export function appendProvisionEvent(event: {
  job_id: number
  level?: 'info' | 'warn' | 'error'
  step_key?: string
  message: string
  data?: any
}) {
  const prisma = getPrismaClient()
  const now = Math.floor(Date.now() / 1000)
  void prisma.provision_events.create({
    data: {
      job_id: event.job_id,
      level: event.level || 'info',
      step_key: event.step_key ?? null,
      message: event.message,
      data: event.data ? JSON.stringify(event.data) : null,
      created_at: now,
    },
    select: { id: true },
  }).catch(() => {
    // ignore
  })
}

function bootstrapIfNeeded() {
  // Some unit tests mock `config` without `dbProvider`; default to sqlite in that case.
  const provider = (config as any).dbProvider ?? 'sqlite'
  if (typeof window !== 'undefined' || isBuildPhase) return

  try {
    if (provider === 'sqlite') {
      bootstrapSqliteSchemaIfNeeded()
    }
    ensureRuntimeListenersInitialized()
    void seedAdminUserFromEnvPrisma().catch(() => {
      // best-effort
    })
  } catch (error) {
    logger.error({ err: error }, 'Failed to initialize database')
  }
}

bootstrapIfNeeded()
