import { describe, it, expect, vi, beforeEach } from 'vitest'

// Use vi.hoisted() so mock variables are available inside vi.mock() factories
const {
  mockBroadcast,
  mockActivitiesCreate,
  mockNotificationsCreate,
  mockAgentsFindFirst,
  mockAgentsUpdateMany,
} = vi.hoisted(() => {
  const mockBroadcast = vi.fn()
  const mockActivitiesCreate = vi.fn(async () => ({ id: 1 }))
  const mockNotificationsCreate = vi.fn(async () => ({ id: 1 }))
  const mockAgentsFindFirst = vi.fn(async () => ({ id: 42 }))
  const mockAgentsUpdateMany = vi.fn(async () => ({ count: 1 }))
  return {
    mockBroadcast,
    mockActivitiesCreate,
    mockNotificationsCreate,
    mockAgentsFindFirst,
    mockAgentsUpdateMany,
  }
})

// Mock better-sqlite3 native module to avoid needing compiled bindings
vi.mock('better-sqlite3', () => {
  return {
    default: vi.fn(() => ({
      pragma: vi.fn(),
      prepare: vi.fn(() => ({ all: vi.fn(() => []) })),
      exec: vi.fn(),
      close: vi.fn(),
    })),
  }
})

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))

vi.mock('@/lib/migrations', () => ({
  runMigrations: vi.fn(),
}))

vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

vi.mock('@/lib/password', () => ({
  hashPassword: vi.fn((p: string) => `hashed:${p}`),
  verifyPassword: vi.fn(() => false),
}))

vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}))

vi.mock('@/lib/event-bus', () => ({
  eventBus: { broadcast: mockBroadcast, on: vi.fn(), emit: vi.fn(), setMaxListeners: vi.fn() },
}))

vi.mock('../prisma', () => ({
  getPrismaClient: () => ({
    activities: { create: mockActivitiesCreate },
    notifications: { create: mockNotificationsCreate },
    agents: { findFirst: mockAgentsFindFirst, updateMany: mockAgentsUpdateMany },
  }),
}))

async function flushAsync() {
  await Promise.resolve()
  await new Promise((r) => setTimeout(r, 0))
}

// Import after mocks — the real db_helpers will use our mocked Prisma client
import { db_helpers } from '@/lib/db'

describe('parseMentions', () => {
  it('extracts multiple mentions', () => {
    expect(db_helpers.parseMentions('@alice hello @bob')).toEqual(['alice', 'bob'])
  })

  it('returns empty array when no mentions', () => {
    expect(db_helpers.parseMentions('no mentions here')).toEqual([])
  })

  it('extracts single mention', () => {
    expect(db_helpers.parseMentions('hey @alice')).toEqual(['alice'])
  })

  it('handles @@double — captures word chars after @', () => {
    const result = db_helpers.parseMentions('@@double')
    expect(result).toContain('double')
  })

  it('handles mentions at start and end of string', () => {
    expect(db_helpers.parseMentions('@start and @end')).toEqual(['start', 'end'])
  })

  it('supports hyphen, underscore, and dots in handles', () => {
    expect(db_helpers.parseMentions('ping @agent-code_reviewer.v2 now')).toEqual(['agent-code_reviewer.v2'])
  })

  it('deduplicates repeated mentions case-insensitively', () => {
    expect(db_helpers.parseMentions('@Alice please sync with @alice')).toEqual(['Alice'])
  })

  it('returns empty array for empty string', () => {
    expect(db_helpers.parseMentions('')).toEqual([])
  })
})

describe('logActivity', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('inserts activity into database and broadcasts event', async () => {
    db_helpers.logActivity('task_created', 'task', 1, 'alice', 'Created task')

    await flushAsync()

    expect(mockActivitiesCreate).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        type: 'task_created',
        entity_type: 'task',
        entity_id: 1,
        actor: 'alice',
        description: 'Created task',
        data: null,
        workspace_id: 1,
        created_at: expect.any(Number),
      }),
    }))
    expect(mockBroadcast).toHaveBeenCalledWith(
      'activity.created',
      expect.objectContaining({
        type: 'task_created',
        entity_type: 'task',
        entity_id: 1,
        actor: 'alice',
      }),
    )
  })

  it('stringifies data when provided', async () => {
    const data = { key: 'value' }
    db_helpers.logActivity('update', 'agent', 2, 'bob', 'Updated agent', data)

    await flushAsync()

    expect(mockActivitiesCreate).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        type: 'update',
        entity_type: 'agent',
        entity_id: 2,
        actor: 'bob',
        description: 'Updated agent',
        data: JSON.stringify(data),
      }),
    }))
  })
})

describe('createNotification', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('inserts notification and broadcasts event', async () => {
    db_helpers.createNotification('alice', 'mention', 'Mentioned', 'You were mentioned')

    await flushAsync()

    expect(mockNotificationsCreate).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        recipient: 'alice',
        type: 'mention',
        title: 'Mentioned',
        message: 'You were mentioned',
        source_type: null,
        source_id: null,
        workspace_id: 1,
        created_at: expect.any(Number),
      }),
    }))
    expect(mockBroadcast).toHaveBeenCalledWith(
      'notification.created',
      expect.objectContaining({
        recipient: 'alice',
        type: 'mention',
        title: 'Mentioned',
      }),
    )
  })

  it('passes source_type and source_id when provided', async () => {
    db_helpers.createNotification('bob', 'alert', 'Alert', 'CPU high', 'agent', 5)

    await flushAsync()

    expect(mockNotificationsCreate).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        recipient: 'bob',
        type: 'alert',
        title: 'Alert',
        message: 'CPU high',
        source_type: 'agent',
        source_id: 5,
        workspace_id: 1,
      }),
    }))
  })
})

describe('updateAgentStatus', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockAgentsFindFirst.mockResolvedValue({ id: 42 })
  })

  it('updates agent status in database and broadcasts', async () => {
    db_helpers.updateAgentStatus('worker-1', 'busy', 'Processing task')

    await flushAsync()

    expect(mockAgentsUpdateMany).toHaveBeenCalledWith(expect.objectContaining({
      where: { name: 'worker-1', workspace_id: 1 },
      data: expect.objectContaining({
        status: 'busy',
        last_activity: 'Processing task',
        last_seen: expect.any(Number),
        updated_at: expect.any(Number),
      }),
    }))
    expect(mockBroadcast).toHaveBeenCalledWith(
      'agent.status_changed',
      expect.objectContaining({
        id: 42,
        name: 'worker-1',
        status: 'busy',
      }),
    )
  })
})
